(* ==================================================================== *)
(* CGLazyROOneSeeded: CG_seedbased twin of LazyROOneSeeded                 *)
(*                                                                        *)
(* CGLazyROOneSeeded.game is structurally identical to LazyROOneSeeded.game *)
(* -- the only difference is that the second codomain half is NG.Nseed     *)
(* (the nominal-group seed) instead of KEM_T.Nseed.  In the EasyCrypt       *)
(* model both halves are abstract types (`pqh`, `th`) with arbitrary        *)
(* lossless distributions, and the seed domain is an abstract type with an  *)
(* arbitrary distribution, so the generic theory LazyROOneSeeded proves     *)
(* this game too: it is the same "one generic theory, two clones" family    *)
(* as LazyROTwoSeeded / CGLazyROTwoSeeded.                                  *)
(*                                                                        *)
(* We import that theory here so the advantage bound (`adv_bound`, an      *)
(* EQUALITY of probabilities, i.e. advantage exactly 0) is checked and     *)
(* available co-located with CGLazyROOneSeeded.game.  Nothing is           *)
(* specialized: the KEM_PQ/KEM_T and KEM_PQ/NG instantiations are the same *)
(* abstract generic statement.                                             *)
(* ==================================================================== *)

require import LazyROOneSeeded.
